export interface Airport {
  city: string;
  name: string;
  iata: string;
  country: string;
}

const airports: Airport[] = [
  // --- Top Global Hubs (by passenger traffic) ---
  { city: "Dubai", name: "Dubai International", iata: "DXB", country: "United Arab Emirates" },
  { city: "London", name: "Heathrow", iata: "LHR", country: "United Kingdom" },
  { city: "Istanbul", name: "Istanbul Airport", iata: "IST", country: "Turkey" },
  { city: "Atlanta", name: "Hartsfield-Jackson International", iata: "ATL", country: "United States" },
  { city: "Dallas", name: "Dallas/Fort Worth International", iata: "DFW", country: "United States" },
  { city: "Denver", name: "Denver International", iata: "DEN", country: "United States" },
  { city: "Chicago", name: "O'Hare International", iata: "ORD", country: "United States" },
  { city: "Los Angeles", name: "Los Angeles International", iata: "LAX", country: "United States" },
  { city: "Tokyo", name: "Haneda", iata: "HND", country: "Japan" },
  { city: "Paris", name: "Charles de Gaulle", iata: "CDG", country: "France" },
  { city: "Delhi", name: "Indira Gandhi International", iata: "DEL", country: "India" },
  { city: "Amsterdam", name: "Schiphol", iata: "AMS", country: "Netherlands" },
  { city: "Guangzhou", name: "Baiyun International", iata: "CAN", country: "China" },
  { city: "Singapore", name: "Changi", iata: "SIN", country: "Singapore" },
  { city: "Shanghai", name: "Pudong International", iata: "PVG", country: "China" },
  { city: "Seoul", name: "Incheon International", iata: "ICN", country: "South Korea" },
  { city: "New York", name: "John F. Kennedy International", iata: "JFK", country: "United States" },
  { city: "Bangkok", name: "Suvarnabhumi", iata: "BKK", country: "Thailand" },
  { city: "Doha", name: "Hamad International", iata: "DOH", country: "Qatar" },
  { city: "Frankfurt", name: "Frankfurt am Main", iata: "FRA", country: "Germany" },
  { city: "Hong Kong", name: "Hong Kong International", iata: "HKG", country: "Hong Kong" },
  { city: "Madrid", name: "Adolfo Suárez Madrid–Barajas", iata: "MAD", country: "Spain" },
  { city: "Mexico City", name: "Benito Juárez International", iata: "MEX", country: "Mexico" },
  { city: "Mumbai", name: "Chhatrapati Shivaji Maharaj International", iata: "BOM", country: "India" },
  { city: "São Paulo", name: "Guarulhos International", iata: "GRU", country: "Brazil" },
  { city: "Orlando", name: "Orlando International", iata: "MCO", country: "United States" },
  { city: "Munich", name: "Franz Josef Strauss", iata: "MUC", country: "Germany" },
  { city: "Toronto", name: "Pearson International", iata: "YYZ", country: "Canada" },
  { city: "Barcelona", name: "Josep Tarradellas Barcelona–El Prat", iata: "BCN", country: "Spain" },
  { city: "Charlotte", name: "Charlotte Douglas International", iata: "CLT", country: "United States" },
  { city: "Beijing", name: "Capital International", iata: "PEK", country: "China" },
  { city: "Kuala Lumpur", name: "Kuala Lumpur International", iata: "KUL", country: "Malaysia" },
  { city: "Miami", name: "Miami International", iata: "MIA", country: "United States" },
  { city: "Jakarta", name: "Soekarno-Hatta International", iata: "CGK", country: "Indonesia" },
  { city: "San Francisco", name: "San Francisco International", iata: "SFO", country: "United States" },
  { city: "Seattle", name: "Seattle-Tacoma International", iata: "SEA", country: "United States" },
  { city: "Rome", name: "Leonardo da Vinci–Fiumicino", iata: "FCO", country: "Italy" },
  { city: "Las Vegas", name: "Harry Reid International", iata: "LAS", country: "United States" },
  { city: "Newark", name: "Newark Liberty International", iata: "EWR", country: "United States" },
  { city: "Abu Dhabi", name: "Zayed International", iata: "AUH", country: "United Arab Emirates" },
  { city: "Sydney", name: "Kingsford Smith", iata: "SYD", country: "Australia" },
  { city: "Zurich", name: "Zurich Airport", iata: "ZRH", country: "Switzerland" },
  { city: "Bogotá", name: "El Dorado International", iata: "BOG", country: "Colombia" },
  { city: "Jeddah", name: "King Abdulaziz International", iata: "JED", country: "Saudi Arabia" },
  { city: "Riyadh", name: "King Khalid International", iata: "RUH", country: "Saudi Arabia" },
  { city: "Cancún", name: "Cancún International", iata: "CUN", country: "Mexico" },
  { city: "Houston", name: "George Bush Intercontinental", iata: "IAH", country: "United States" },
  { city: "Lisbon", name: "Humberto Delgado", iata: "LIS", country: "Portugal" },
  { city: "Dublin", name: "Dublin Airport", iata: "DUB", country: "Ireland" },
  { city: "Phoenix", name: "Sky Harbor International", iata: "PHX", country: "United States" },

  // --- Middle East & Gulf ---
  { city: "Muscat", name: "Muscat International", iata: "MCT", country: "Oman" },
  { city: "Bahrain", name: "Bahrain International", iata: "BAH", country: "Bahrain" },
  { city: "Kuwait City", name: "Kuwait International", iata: "KWI", country: "Kuwait" },
  { city: "Amman", name: "Queen Alia International", iata: "AMM", country: "Jordan" },
  { city: "Beirut", name: "Rafic Hariri International", iata: "BEY", country: "Lebanon" },
  { city: "Tel Aviv", name: "Ben Gurion", iata: "TLV", country: "Israel" },
  { city: "Cairo", name: "Cairo International", iata: "CAI", country: "Egypt" },
  { city: "Medina", name: "Prince Mohammad bin Abdulaziz International", iata: "MED", country: "Saudi Arabia" },
  { city: "Dammam", name: "King Fahd International", iata: "DMM", country: "Saudi Arabia" },
  { city: "Sharjah", name: "Sharjah International", iata: "SHJ", country: "United Arab Emirates" },
  { city: "Erbil", name: "Erbil International", iata: "EBL", country: "Iraq" },
  { city: "Baghdad", name: "Baghdad International", iata: "BGW", country: "Iraq" },
  { city: "Tehran", name: "Imam Khomeini International", iata: "IKA", country: "Iran" },
  { city: "Sharm El Sheikh", name: "Sharm El Sheikh International", iata: "SSH", country: "Egypt" },
  { city: "Hurghada", name: "Hurghada International", iata: "HRG", country: "Egypt" },
  { city: "Al Ain", name: "Al Ain International", iata: "AAN", country: "United Arab Emirates" },
  { city: "Salalah", name: "Salalah Airport", iata: "SLL", country: "Oman" },
  { city: "NEOM", name: "NEOM Bay Airport", iata: "NUM", country: "Saudi Arabia" },
  { city: "Tabuk", name: "Prince Sultan bin Abdulaziz Airport", iata: "TUU", country: "Saudi Arabia" },
  { city: "AlUla", name: "Prince Abdul Majeed bin Abdulaziz Airport", iata: "ULH", country: "Saudi Arabia" },

  // --- Europe ---
  { city: "London", name: "Gatwick", iata: "LGW", country: "United Kingdom" },
  { city: "London", name: "Stansted", iata: "STN", country: "United Kingdom" },
  { city: "London", name: "Luton", iata: "LTN", country: "United Kingdom" },
  { city: "London", name: "City Airport", iata: "LCY", country: "United Kingdom" },
  { city: "Manchester", name: "Manchester Airport", iata: "MAN", country: "United Kingdom" },
  { city: "Edinburgh", name: "Edinburgh Airport", iata: "EDI", country: "United Kingdom" },
  { city: "Birmingham", name: "Birmingham Airport", iata: "BHX", country: "United Kingdom" },
  { city: "Glasgow", name: "Glasgow Airport", iata: "GLA", country: "United Kingdom" },
  { city: "Bristol", name: "Bristol Airport", iata: "BRS", country: "United Kingdom" },
  { city: "Paris", name: "Orly", iata: "ORY", country: "France" },
  { city: "Paris", name: "Le Bourget", iata: "LBG", country: "France" },
  { city: "Nice", name: "Côte d'Azur", iata: "NCE", country: "France" },
  { city: "Lyon", name: "Saint-Exupéry", iata: "LYS", country: "France" },
  { city: "Marseille", name: "Provence", iata: "MRS", country: "France" },
  { city: "Toulouse", name: "Blagnac", iata: "TLS", country: "France" },
  { city: "Bordeaux", name: "Mérignac", iata: "BOD", country: "France" },
  { city: "Berlin", name: "Brandenburg", iata: "BER", country: "Germany" },
  { city: "Hamburg", name: "Hamburg Airport", iata: "HAM", country: "Germany" },
  { city: "Düsseldorf", name: "Düsseldorf Airport", iata: "DUS", country: "Germany" },
  { city: "Cologne", name: "Cologne Bonn", iata: "CGN", country: "Germany" },
  { city: "Stuttgart", name: "Stuttgart Airport", iata: "STR", country: "Germany" },
  { city: "Hanover", name: "Hanover Airport", iata: "HAJ", country: "Germany" },
  { city: "Rome", name: "Ciampino", iata: "CIA", country: "Italy" },
  { city: "Milan", name: "Malpensa", iata: "MXP", country: "Italy" },
  { city: "Milan", name: "Linate", iata: "LIN", country: "Italy" },
  { city: "Venice", name: "Marco Polo", iata: "VCE", country: "Italy" },
  { city: "Naples", name: "Naples International", iata: "NAP", country: "Italy" },
  { city: "Florence", name: "Peretola", iata: "FLR", country: "Italy" },
  { city: "Bologna", name: "Guglielmo Marconi", iata: "BLQ", country: "Italy" },
  { city: "Catania", name: "Fontanarossa", iata: "CTA", country: "Italy" },
  { city: "Palermo", name: "Falcone Borsellino", iata: "PMO", country: "Italy" },
  { city: "Vienna", name: "Vienna International", iata: "VIE", country: "Austria" },
  { city: "Salzburg", name: "Salzburg Airport", iata: "SZG", country: "Austria" },
  { city: "Innsbruck", name: "Innsbruck Airport", iata: "INN", country: "Austria" },
  { city: "Brussels", name: "Brussels Airport", iata: "BRU", country: "Belgium" },
  { city: "Geneva", name: "Geneva Airport", iata: "GVA", country: "Switzerland" },
  { city: "Basel", name: "EuroAirport Basel-Mulhouse", iata: "BSL", country: "Switzerland" },
  { city: "Copenhagen", name: "Kastrup", iata: "CPH", country: "Denmark" },
  { city: "Oslo", name: "Gardermoen", iata: "OSL", country: "Norway" },
  { city: "Bergen", name: "Flesland", iata: "BGO", country: "Norway" },
  { city: "Stockholm", name: "Arlanda", iata: "ARN", country: "Sweden" },
  { city: "Gothenburg", name: "Landvetter", iata: "GOT", country: "Sweden" },
  { city: "Helsinki", name: "Helsinki-Vantaa", iata: "HEL", country: "Finland" },
  { city: "Warsaw", name: "Chopin Airport", iata: "WAW", country: "Poland" },
  { city: "Kraków", name: "John Paul II International", iata: "KRK", country: "Poland" },
  { city: "Prague", name: "Václav Havel", iata: "PRG", country: "Czech Republic" },
  { city: "Budapest", name: "Ferenc Liszt International", iata: "BUD", country: "Hungary" },
  { city: "Bucharest", name: "Henri Coandă International", iata: "OTP", country: "Romania" },
  { city: "Athens", name: "Eleftherios Venizelos", iata: "ATH", country: "Greece" },
  { city: "Thessaloniki", name: "Makedonia", iata: "SKG", country: "Greece" },
  { city: "Mykonos", name: "Mykonos Airport", iata: "JMK", country: "Greece" },
  { city: "Santorini", name: "Santorini Airport", iata: "JTR", country: "Greece" },
  { city: "Heraklion", name: "Nikos Kazantzakis", iata: "HER", country: "Greece" },
  { city: "Corfu", name: "Ioannis Kapodistrias", iata: "CFU", country: "Greece" },
  { city: "Rhodes", name: "Diagoras", iata: "RHO", country: "Greece" },
  { city: "Istanbul", name: "Sabiha Gökçen", iata: "SAW", country: "Turkey" },
  { city: "Antalya", name: "Antalya Airport", iata: "AYT", country: "Turkey" },
  { city: "Ankara", name: "Esenboğa", iata: "ESB", country: "Turkey" },
  { city: "Izmir", name: "Adnan Menderes", iata: "ADB", country: "Turkey" },
  { city: "Bodrum", name: "Milas-Bodrum", iata: "BJV", country: "Turkey" },
  { city: "Dalaman", name: "Dalaman Airport", iata: "DLM", country: "Turkey" },
  { city: "Porto", name: "Francisco Sá Carneiro", iata: "OPO", country: "Portugal" },
  { city: "Faro", name: "Faro Airport", iata: "FAO", country: "Portugal" },
  { city: "Malaga", name: "Costa del Sol", iata: "AGP", country: "Spain" },
  { city: "Palma de Mallorca", name: "Son Sant Joan", iata: "PMI", country: "Spain" },
  { city: "Ibiza", name: "Ibiza Airport", iata: "IBZ", country: "Spain" },
  { city: "Tenerife", name: "Tenerife South", iata: "TFS", country: "Spain" },
  { city: "Gran Canaria", name: "Gran Canaria Airport", iata: "LPA", country: "Spain" },
  { city: "Valencia", name: "Valencia Airport", iata: "VLC", country: "Spain" },
  { city: "Seville", name: "San Pablo", iata: "SVQ", country: "Spain" },
  { city: "Bilbao", name: "Bilbao Airport", iata: "BIO", country: "Spain" },
  { city: "Alicante", name: "Alicante-Elche Miguel Hernández", iata: "ALC", country: "Spain" },
  { city: "Moscow", name: "Sheremetyevo", iata: "SVO", country: "Russia" },
  { city: "Moscow", name: "Domodedovo", iata: "DME", country: "Russia" },
  { city: "Moscow", name: "Vnukovo", iata: "VKO", country: "Russia" },
  { city: "Saint Petersburg", name: "Pulkovo", iata: "LED", country: "Russia" },
  { city: "Reykjavik", name: "Keflavík International", iata: "KEF", country: "Iceland" },
  { city: "Dubrovnik", name: "Dubrovnik Airport", iata: "DBV", country: "Croatia" },
  { city: "Split", name: "Split Airport", iata: "SPU", country: "Croatia" },
  { city: "Zagreb", name: "Franjo Tuđman", iata: "ZAG", country: "Croatia" },
  { city: "Ljubljana", name: "Jože Pučnik", iata: "LJU", country: "Slovenia" },
  { city: "Belgrade", name: "Nikola Tesla", iata: "BEG", country: "Serbia" },
  { city: "Sofia", name: "Sofia Airport", iata: "SOF", country: "Bulgaria" },
  { city: "Kyiv", name: "Boryspil International", iata: "KBP", country: "Ukraine" },
  { city: "Riga", name: "Riga International", iata: "RIX", country: "Latvia" },
  { city: "Vilnius", name: "Vilnius Airport", iata: "VNO", country: "Lithuania" },
  { city: "Tallinn", name: "Lennart Meri", iata: "TLL", country: "Estonia" },
  { city: "Malta", name: "Malta International", iata: "MLA", country: "Malta" },
  { city: "Luxembourg", name: "Luxembourg Airport", iata: "LUX", country: "Luxembourg" },
  { city: "Tirana", name: "Tirana International", iata: "TIA", country: "Albania" },
  { city: "Podgorica", name: "Podgorica Airport", iata: "TGD", country: "Montenegro" },
  { city: "Tivat", name: "Tivat Airport", iata: "TIV", country: "Montenegro" },
  { city: "Larnaca", name: "Larnaca International", iata: "LCA", country: "Cyprus" },
  { city: "Paphos", name: "Paphos International", iata: "PFO", country: "Cyprus" },

  // --- North America ---
  { city: "New York", name: "LaGuardia", iata: "LGA", country: "United States" },
  { city: "Boston", name: "Logan International", iata: "BOS", country: "United States" },
  { city: "Washington", name: "Dulles International", iata: "IAD", country: "United States" },
  { city: "Washington", name: "Ronald Reagan National", iata: "DCA", country: "United States" },
  { city: "Philadelphia", name: "Philadelphia International", iata: "PHL", country: "United States" },
  { city: "Minneapolis", name: "Minneapolis-Saint Paul International", iata: "MSP", country: "United States" },
  { city: "Detroit", name: "Detroit Metropolitan Wayne County", iata: "DTW", country: "United States" },
  { city: "Fort Lauderdale", name: "Fort Lauderdale-Hollywood International", iata: "FLL", country: "United States" },
  { city: "Tampa", name: "Tampa International", iata: "TPA", country: "United States" },
  { city: "San Diego", name: "San Diego International", iata: "SAN", country: "United States" },
  { city: "Baltimore", name: "Baltimore/Washington International", iata: "BWI", country: "United States" },
  { city: "Salt Lake City", name: "Salt Lake City International", iata: "SLC", country: "United States" },
  { city: "Nashville", name: "Nashville International", iata: "BNA", country: "United States" },
  { city: "Austin", name: "Austin-Bergstrom International", iata: "AUS", country: "United States" },
  { city: "Portland", name: "Portland International", iata: "PDX", country: "United States" },
  { city: "San Jose", name: "Norman Y. Mineta San José International", iata: "SJC", country: "United States" },
  { city: "Raleigh", name: "Raleigh-Durham International", iata: "RDU", country: "United States" },
  { city: "St. Louis", name: "St. Louis Lambert International", iata: "STL", country: "United States" },
  { city: "Kansas City", name: "Kansas City International", iata: "MCI", country: "United States" },
  { city: "Indianapolis", name: "Indianapolis International", iata: "IND", country: "United States" },
  { city: "Cleveland", name: "Cleveland Hopkins International", iata: "CLE", country: "United States" },
  { city: "Pittsburgh", name: "Pittsburgh International", iata: "PIT", country: "United States" },
  { city: "Cincinnati", name: "Cincinnati/Northern Kentucky International", iata: "CVG", country: "United States" },
  { city: "Columbus", name: "John Glenn International", iata: "CMH", country: "United States" },
  { city: "San Antonio", name: "San Antonio International", iata: "SAT", country: "United States" },
  { city: "New Orleans", name: "Louis Armstrong New Orleans International", iata: "MSY", country: "United States" },
  { city: "Oakland", name: "Oakland International", iata: "OAK", country: "United States" },
  { city: "Milwaukee", name: "General Mitchell International", iata: "MKE", country: "United States" },
  { city: "Honolulu", name: "Daniel K. Inouye International", iata: "HNL", country: "United States" },
  { city: "Anchorage", name: "Ted Stevens Anchorage International", iata: "ANC", country: "United States" },
  { city: "Jacksonville", name: "Jacksonville International", iata: "JAX", country: "United States" },
  { city: "Memphis", name: "Memphis International", iata: "MEM", country: "United States" },
  { city: "Richmond", name: "Richmond International", iata: "RIC", country: "United States" },
  { city: "Hartford", name: "Bradley International", iata: "BDL", country: "United States" },
  { city: "Buffalo", name: "Buffalo Niagara International", iata: "BUF", country: "United States" },
  { city: "Teterboro", name: "Teterboro Airport", iata: "TEB", country: "United States" },
  { city: "Van Nuys", name: "Van Nuys Airport", iata: "VNY", country: "United States" },
  { city: "White Plains", name: "Westchester County", iata: "HPN", country: "United States" },
  { city: "Palm Beach", name: "Palm Beach International", iata: "PBI", country: "United States" },
  { city: "Naples", name: "Naples Municipal", iata: "APF", country: "United States" },
  { city: "Scottsdale", name: "Scottsdale Airport", iata: "SCF", country: "United States" },
  { city: "Aspen", name: "Aspen/Pitkin County", iata: "ASE", country: "United States" },
  { city: "Jackson Hole", name: "Jackson Hole Airport", iata: "JAC", country: "United States" },
  { city: "Martha's Vineyard", name: "Martha's Vineyard Airport", iata: "MVY", country: "United States" },
  { city: "Nantucket", name: "Nantucket Memorial", iata: "ACK", country: "United States" },
  { city: "Key West", name: "Key West International", iata: "EYW", country: "United States" },
  { city: "Maui", name: "Kahului Airport", iata: "OGG", country: "United States" },
  { city: "Montreal", name: "Pierre Elliott Trudeau International", iata: "YUL", country: "Canada" },
  { city: "Vancouver", name: "Vancouver International", iata: "YVR", country: "Canada" },
  { city: "Calgary", name: "Calgary International", iata: "YYC", country: "Canada" },
  { city: "Edmonton", name: "Edmonton International", iata: "YEG", country: "Canada" },
  { city: "Ottawa", name: "Ottawa Macdonald-Cartier International", iata: "YOW", country: "Canada" },
  { city: "Winnipeg", name: "Winnipeg James Armstrong Richardson International", iata: "YWG", country: "Canada" },
  { city: "Halifax", name: "Halifax Stanfield International", iata: "YHZ", country: "Canada" },
  { city: "Quebec City", name: "Jean Lesage International", iata: "YQB", country: "Canada" },

  // --- Caribbean ---
  { city: "Nassau", name: "Lynden Pindling International", iata: "NAS", country: "Bahamas" },
  { city: "Montego Bay", name: "Sangster International", iata: "MBJ", country: "Jamaica" },
  { city: "Kingston", name: "Norman Manley International", iata: "KIN", country: "Jamaica" },
  { city: "Punta Cana", name: "Punta Cana International", iata: "PUJ", country: "Dominican Republic" },
  { city: "Santo Domingo", name: "Las Américas International", iata: "SDQ", country: "Dominican Republic" },
  { city: "San Juan", name: "Luis Muñoz Marín International", iata: "SJU", country: "Puerto Rico" },
  { city: "Bridgetown", name: "Grantley Adams International", iata: "BGI", country: "Barbados" },
  { city: "Port of Spain", name: "Piarco International", iata: "POS", country: "Trinidad and Tobago" },
  { city: "Havana", name: "José Martí International", iata: "HAV", country: "Cuba" },
  { city: "Aruba", name: "Queen Beatrix International", iata: "AUA", country: "Aruba" },
  { city: "Curaçao", name: "Hato International", iata: "CUR", country: "Curaçao" },
  { city: "Grand Cayman", name: "Owen Roberts International", iata: "GCM", country: "Cayman Islands" },
  { city: "St. Maarten", name: "Princess Juliana International", iata: "SXM", country: "Sint Maarten" },
  { city: "Antigua", name: "V.C. Bird International", iata: "ANU", country: "Antigua and Barbuda" },
  { city: "St. Thomas", name: "Cyril E. King", iata: "STT", country: "US Virgin Islands" },
  { city: "Turks and Caicos", name: "Providenciales International", iata: "PLS", country: "Turks and Caicos" },
  { city: "Bermuda", name: "L.F. Wade International", iata: "BDA", country: "Bermuda" },
  { city: "St. Lucia", name: "Hewanorra International", iata: "UVF", country: "Saint Lucia" },
  { city: "St. Kitts", name: "Robert L. Bradshaw International", iata: "SKB", country: "Saint Kitts and Nevis" },
  { city: "Grenada", name: "Maurice Bishop International", iata: "GND", country: "Grenada" },

  // --- Latin America ---
  { city: "São Paulo", name: "Congonhas", iata: "CGH", country: "Brazil" },
  { city: "Rio de Janeiro", name: "Galeão International", iata: "GIG", country: "Brazil" },
  { city: "Rio de Janeiro", name: "Santos Dumont", iata: "SDU", country: "Brazil" },
  { city: "Brasília", name: "Presidente Juscelino Kubitschek", iata: "BSB", country: "Brazil" },
  { city: "Buenos Aires", name: "Ministro Pistarini International (Ezeiza)", iata: "EZE", country: "Argentina" },
  { city: "Buenos Aires", name: "Aeroparque Jorge Newbery", iata: "AEP", country: "Argentina" },
  { city: "Santiago", name: "Arturo Merino Benítez International", iata: "SCL", country: "Chile" },
  { city: "Lima", name: "Jorge Chávez International", iata: "LIM", country: "Peru" },
  { city: "Panama City", name: "Tocumen International", iata: "PTY", country: "Panama" },
  { city: "San José", name: "Juan Santamaría International", iata: "SJO", country: "Costa Rica" },
  { city: "Medellín", name: "José María Córdova International", iata: "MDE", country: "Colombia" },
  { city: "Cartagena", name: "Rafael Núñez International", iata: "CTG", country: "Colombia" },
  { city: "Quito", name: "Mariscal Sucre International", iata: "UIO", country: "Ecuador" },
  { city: "Guayaquil", name: "José Joaquín de Olmedo International", iata: "GYE", country: "Ecuador" },
  { city: "Montevideo", name: "Carrasco International", iata: "MVD", country: "Uruguay" },
  { city: "Guadalajara", name: "Miguel Hidalgo y Costilla International", iata: "GDL", country: "Mexico" },
  { city: "Monterrey", name: "Mariano Escobedo International", iata: "MTY", country: "Mexico" },
  { city: "Los Cabos", name: "Los Cabos International", iata: "SJD", country: "Mexico" },
  { city: "Puerto Vallarta", name: "Gustavo Díaz Ordaz International", iata: "PVR", country: "Mexico" },
  { city: "Caracas", name: "Simón Bolívar International", iata: "CCS", country: "Venezuela" },
  { city: "Asunción", name: "Silvio Pettirossi International", iata: "ASU", country: "Paraguay" },
  { city: "La Paz", name: "El Alto International", iata: "LPB", country: "Bolivia" },
  { city: "Guatemala City", name: "La Aurora International", iata: "GUA", country: "Guatemala" },
  { city: "San Salvador", name: "Óscar Arnulfo Romero International", iata: "SAL", country: "El Salvador" },
  { city: "Tegucigalpa", name: "Toncontín International", iata: "TGU", country: "Honduras" },

  // --- Asia ---
  { city: "Tokyo", name: "Narita International", iata: "NRT", country: "Japan" },
  { city: "Osaka", name: "Kansai International", iata: "KIX", country: "Japan" },
  { city: "Nagoya", name: "Chūbu Centrair International", iata: "NGO", country: "Japan" },
  { city: "Fukuoka", name: "Fukuoka Airport", iata: "FUK", country: "Japan" },
  { city: "Sapporo", name: "New Chitose", iata: "CTS", country: "Japan" },
  { city: "Seoul", name: "Gimpo International", iata: "GMP", country: "South Korea" },
  { city: "Busan", name: "Gimhae International", iata: "PUS", country: "South Korea" },
  { city: "Jeju", name: "Jeju International", iata: "CJU", country: "South Korea" },
  { city: "Beijing", name: "Daxing International", iata: "PKX", country: "China" },
  { city: "Shanghai", name: "Hongqiao International", iata: "SHA", country: "China" },
  { city: "Shenzhen", name: "Bao'an International", iata: "SZX", country: "China" },
  { city: "Chengdu", name: "Tianfu International", iata: "TFU", country: "China" },
  { city: "Chongqing", name: "Jiangbei International", iata: "CKG", country: "China" },
  { city: "Kunming", name: "Changshui International", iata: "KMG", country: "China" },
  { city: "Xi'an", name: "Xianyang International", iata: "XIY", country: "China" },
  { city: "Hangzhou", name: "Xiaoshan International", iata: "HGH", country: "China" },
  { city: "Wuhan", name: "Tianhe International", iata: "WUH", country: "China" },
  { city: "Nanjing", name: "Lukou International", iata: "NKG", country: "China" },
  { city: "Haikou", name: "Meilan International", iata: "HAK", country: "China" },
  { city: "Macau", name: "Macau International", iata: "MFM", country: "Macau" },
  { city: "Taipei", name: "Taiwan Taoyuan International", iata: "TPE", country: "Taiwan" },
  { city: "Taipei", name: "Songshan", iata: "TSA", country: "Taiwan" },
  { city: "Kaohsiung", name: "Kaohsiung International", iata: "KHH", country: "Taiwan" },
  { city: "Bangkok", name: "Don Mueang", iata: "DMK", country: "Thailand" },
  { city: "Phuket", name: "Phuket International", iata: "HKT", country: "Thailand" },
  { city: "Chiang Mai", name: "Chiang Mai International", iata: "CNX", country: "Thailand" },
  { city: "Koh Samui", name: "Samui Airport", iata: "USM", country: "Thailand" },
  { city: "Krabi", name: "Krabi Airport", iata: "KBV", country: "Thailand" },
  { city: "Ho Chi Minh City", name: "Tan Son Nhat International", iata: "SGN", country: "Vietnam" },
  { city: "Hanoi", name: "Noi Bai International", iata: "HAN", country: "Vietnam" },
  { city: "Da Nang", name: "Da Nang International", iata: "DAD", country: "Vietnam" },
  { city: "Manila", name: "Ninoy Aquino International", iata: "MNL", country: "Philippines" },
  { city: "Cebu", name: "Mactan-Cebu International", iata: "CEB", country: "Philippines" },
  { city: "Bali", name: "Ngurah Rai International", iata: "DPS", country: "Indonesia" },
  { city: "Surabaya", name: "Juanda International", iata: "SUB", country: "Indonesia" },
  { city: "Bangalore", name: "Kempegowda International", iata: "BLR", country: "India" },
  { city: "Hyderabad", name: "Rajiv Gandhi International", iata: "HYD", country: "India" },
  { city: "Chennai", name: "Chennai International", iata: "MAA", country: "India" },
  { city: "Kolkata", name: "Netaji Subhas Chandra Bose International", iata: "CCU", country: "India" },
  { city: "Kochi", name: "Cochin International", iata: "COK", country: "India" },
  { city: "Goa", name: "Manohar International", iata: "GOX", country: "India" },
  { city: "Ahmedabad", name: "Sardar Vallabhbhai Patel International", iata: "AMD", country: "India" },
  { city: "Pune", name: "Pune Airport", iata: "PNQ", country: "India" },
  { city: "Jaipur", name: "Jaipur International", iata: "JAI", country: "India" },
  { city: "Colombo", name: "Bandaranaike International", iata: "CMB", country: "Sri Lanka" },
  { city: "Malé", name: "Velana International", iata: "MLE", country: "Maldives" },
  { city: "Kathmandu", name: "Tribhuvan International", iata: "KTM", country: "Nepal" },
  { city: "Dhaka", name: "Hazrat Shahjalal International", iata: "DAC", country: "Bangladesh" },
  { city: "Islamabad", name: "Islamabad International", iata: "ISB", country: "Pakistan" },
  { city: "Karachi", name: "Jinnah International", iata: "KHI", country: "Pakistan" },
  { city: "Lahore", name: "Allama Iqbal International", iata: "LHE", country: "Pakistan" },
  { city: "Phnom Penh", name: "Phnom Penh International", iata: "PNH", country: "Cambodia" },
  { city: "Siem Reap", name: "Siem Reap International", iata: "REP", country: "Cambodia" },
  { city: "Vientiane", name: "Wattay International", iata: "VTE", country: "Laos" },
  { city: "Yangon", name: "Yangon International", iata: "RGN", country: "Myanmar" },
  { city: "Ulaanbaatar", name: "Chinggis Khaan International", iata: "UBN", country: "Mongolia" },
  { city: "Tashkent", name: "Tashkent International", iata: "TAS", country: "Uzbekistan" },
  { city: "Almaty", name: "Almaty International", iata: "ALA", country: "Kazakhstan" },
  { city: "Nur-Sultan", name: "Nursultan Nazarbayev International", iata: "NQZ", country: "Kazakhstan" },
  { city: "Tbilisi", name: "Tbilisi International", iata: "TBS", country: "Georgia" },
  { city: "Baku", name: "Heydar Aliyev International", iata: "GYD", country: "Azerbaijan" },
  { city: "Yerevan", name: "Zvartnots International", iata: "EVN", country: "Armenia" },
  { city: "Brunei", name: "Brunei International", iata: "BWN", country: "Brunei" },
  { city: "Penang", name: "Penang International", iata: "PEN", country: "Malaysia" },
  { city: "Kota Kinabalu", name: "Kota Kinabalu International", iata: "BKI", country: "Malaysia" },
  { city: "Langkawi", name: "Langkawi International", iata: "LGK", country: "Malaysia" },

  // --- Africa ---
  { city: "Johannesburg", name: "O.R. Tambo International", iata: "JNB", country: "South Africa" },
  { city: "Cape Town", name: "Cape Town International", iata: "CPT", country: "South Africa" },
  { city: "Durban", name: "King Shaka International", iata: "DUR", country: "South Africa" },
  { city: "Nairobi", name: "Jomo Kenyatta International", iata: "NBO", country: "Kenya" },
  { city: "Lagos", name: "Murtala Muhammed International", iata: "LOS", country: "Nigeria" },
  { city: "Abuja", name: "Nnamdi Azikiwe International", iata: "ABV", country: "Nigeria" },
  { city: "Addis Ababa", name: "Bole International", iata: "ADD", country: "Ethiopia" },
  { city: "Casablanca", name: "Mohammed V International", iata: "CMN", country: "Morocco" },
  { city: "Marrakech", name: "Menara Airport", iata: "RAK", country: "Morocco" },
  { city: "Tangier", name: "Ibn Battouta Airport", iata: "TNG", country: "Morocco" },
  { city: "Tunis", name: "Carthage International", iata: "TUN", country: "Tunisia" },
  { city: "Algiers", name: "Houari Boumediene", iata: "ALG", country: "Algeria" },
  { city: "Accra", name: "Kotoka International", iata: "ACC", country: "Ghana" },
  { city: "Dar es Salaam", name: "Julius Nyerere International", iata: "DAR", country: "Tanzania" },
  { city: "Zanzibar", name: "Abeid Amani Karume International", iata: "ZNZ", country: "Tanzania" },
  { city: "Kilimanjaro", name: "Kilimanjaro International", iata: "JRO", country: "Tanzania" },
  { city: "Entebbe", name: "Entebbe International", iata: "EBB", country: "Uganda" },
  { city: "Kigali", name: "Kigali International", iata: "KGL", country: "Rwanda" },
  { city: "Windhoek", name: "Hosea Kutako International", iata: "WDH", country: "Namibia" },
  { city: "Victoria Falls", name: "Victoria Falls Airport", iata: "VFA", country: "Zimbabwe" },
  { city: "Harare", name: "Robert Gabriel Mugabe International", iata: "HRE", country: "Zimbabwe" },
  { city: "Lusaka", name: "Kenneth Kaunda International", iata: "LUN", country: "Zambia" },
  { city: "Maputo", name: "Maputo International", iata: "MPM", country: "Mozambique" },
  { city: "Mauritius", name: "Sir Seewoosagur Ramgoolam International", iata: "MRU", country: "Mauritius" },
  { city: "Seychelles", name: "Seychelles International", iata: "SEZ", country: "Seychelles" },
  { city: "Dakar", name: "Blaise Diagne International", iata: "DSS", country: "Senegal" },
  { city: "Abidjan", name: "Félix-Houphouët-Boigny International", iata: "ABJ", country: "Ivory Coast" },
  { city: "Luanda", name: "Quatro de Fevereiro", iata: "LAD", country: "Angola" },
  { city: "Kinshasa", name: "N'djili International", iata: "FIH", country: "Democratic Republic of the Congo" },
  { city: "Libreville", name: "Léon-Mba International", iata: "LBV", country: "Gabon" },
  { city: "Douala", name: "Douala International", iata: "DLA", country: "Cameroon" },
  { city: "Antananarivo", name: "Ivato International", iata: "TNR", country: "Madagascar" },

  // --- Oceania ---
  { city: "Melbourne", name: "Melbourne Airport", iata: "MEL", country: "Australia" },
  { city: "Brisbane", name: "Brisbane Airport", iata: "BNE", country: "Australia" },
  { city: "Perth", name: "Perth Airport", iata: "PER", country: "Australia" },
  { city: "Adelaide", name: "Adelaide Airport", iata: "ADL", country: "Australia" },
  { city: "Gold Coast", name: "Gold Coast Airport", iata: "OOL", country: "Australia" },
  { city: "Cairns", name: "Cairns Airport", iata: "CNS", country: "Australia" },
  { city: "Auckland", name: "Auckland Airport", iata: "AKL", country: "New Zealand" },
  { city: "Wellington", name: "Wellington International", iata: "WLG", country: "New Zealand" },
  { city: "Christchurch", name: "Christchurch International", iata: "CHC", country: "New Zealand" },
  { city: "Queenstown", name: "Queenstown Airport", iata: "ZQN", country: "New Zealand" },
  { city: "Fiji", name: "Nadi International", iata: "NAN", country: "Fiji" },
  { city: "Tahiti", name: "Faa'a International", iata: "PPT", country: "French Polynesia" },
  { city: "Bora Bora", name: "Bora Bora Airport", iata: "BOB", country: "French Polynesia" },
  { city: "Nouméa", name: "La Tontouta International", iata: "NOU", country: "New Caledonia" },
  { city: "Guam", name: "Antonio B. Won Pat International", iata: "GUM", country: "Guam" },
  { city: "Port Moresby", name: "Jacksons International", iata: "POM", country: "Papua New Guinea" },

  // --- Additional Private Jet Popular Destinations ---
  { city: "Monaco", name: "Nice (serving Monaco)", iata: "MCM", country: "Monaco" },
  { city: "Farnborough", name: "Farnborough Airport", iata: "FAB", country: "United Kingdom" },
  { city: "Biggin Hill", name: "Biggin Hill Airport", iata: "BQH", country: "United Kingdom" },
  { city: "Oxford", name: "London Oxford Airport", iata: "OXF", country: "United Kingdom" },
  { city: "Cannes", name: "Cannes-Mandelieu", iata: "CEQ", country: "France" },
  { city: "St. Tropez", name: "La Môle", iata: "LTT", country: "France" },
  { city: "Chambéry", name: "Chambéry Airport", iata: "CMF", country: "France" },
  { city: "Sion", name: "Sion Airport", iata: "SIR", country: "Switzerland" },
  { city: "St. Moritz", name: "Samedan Airport", iata: "SMV", country: "Switzerland" },
  { city: "Lugano", name: "Lugano Airport", iata: "LUG", country: "Switzerland" },
  { city: "Sardinia", name: "Olbia Costa Smeralda", iata: "OLB", country: "Italy" },
  { city: "Lamezia Terme", name: "Lamezia Terme International", iata: "SUF", country: "Italy" },
  { city: "Bari", name: "Karol Wojtyła Airport", iata: "BRI", country: "Italy" },
  { city: "Pisa", name: "Galileo Galilei", iata: "PSA", country: "Italy" },
  { city: "Verona", name: "Villafranca Airport", iata: "VRN", country: "Italy" },
  { city: "Turin", name: "Caselle Airport", iata: "TRN", country: "Italy" },
  { city: "Genoa", name: "Cristoforo Colombo", iata: "GOA", country: "Italy" },
  { city: "Marbella", name: "Malaga (serving Marbella)", iata: "AGP", country: "Spain" },
  { city: "Menorca", name: "Menorca Airport", iata: "MAH", country: "Spain" },
  { city: "Lanzarote", name: "César Manrique-Lanzarote", iata: "ACE", country: "Spain" },
  { city: "Fuerteventura", name: "Fuerteventura Airport", iata: "FUE", country: "Spain" },
  { city: "Girona", name: "Girona-Costa Brava", iata: "GRO", country: "Spain" },
  { city: "Santiago", name: "Santiago de Compostela", iata: "SCQ", country: "Spain" },
  { city: "East Midlands", name: "East Midlands Airport", iata: "EMA", country: "United Kingdom" },
  { city: "Newcastle", name: "Newcastle Airport", iata: "NCL", country: "United Kingdom" },
  { city: "Leeds", name: "Leeds Bradford Airport", iata: "LBA", country: "United Kingdom" },
  { city: "Belfast", name: "Belfast International", iata: "BFS", country: "United Kingdom" },
  { city: "Aberdeen", name: "Aberdeen International", iata: "ABZ", country: "United Kingdom" },
  { city: "Jersey", name: "Jersey Airport", iata: "JER", country: "Jersey" },
  { city: "Guernsey", name: "Guernsey Airport", iata: "GCI", country: "Guernsey" },
  { city: "Isle of Man", name: "Isle of Man Airport", iata: "IOM", country: "Isle of Man" },
  { city: "Eindhoven", name: "Eindhoven Airport", iata: "EIN", country: "Netherlands" },
  { city: "Rotterdam", name: "Rotterdam The Hague", iata: "RTM", country: "Netherlands" },
  { city: "Malmö", name: "Malmö Airport", iata: "MMX", country: "Sweden" },
  { city: "Stavanger", name: "Stavanger Airport", iata: "SVG", country: "Norway" },
  { city: "Tromsø", name: "Tromsø Airport", iata: "TOS", country: "Norway" },
  { city: "Turku", name: "Turku Airport", iata: "TKU", country: "Finland" },
  { city: "Tampere", name: "Tampere-Pirkkala", iata: "TMP", country: "Finland" },
  { city: "Poznan", name: "Ławica Airport", iata: "POZ", country: "Poland" },
  { city: "Gdansk", name: "Lech Wałęsa Airport", iata: "GDN", country: "Poland" },
  { city: "Wroclaw", name: "Copernicus Airport", iata: "WRO", country: "Poland" },
  { city: "Brno", name: "Brno-Tuřany", iata: "BRQ", country: "Czech Republic" },
  { city: "Bratislava", name: "M. R. Štefánik Airport", iata: "BTS", country: "Slovakia" },
  { city: "Cluj-Napoca", name: "Avram Iancu International", iata: "CLJ", country: "Romania" },
  { city: "Varna", name: "Varna Airport", iata: "VAR", country: "Bulgaria" },
  { city: "Skopje", name: "Skopje International", iata: "SKP", country: "North Macedonia" },
  { city: "Sarajevo", name: "Sarajevo International", iata: "SJJ", country: "Bosnia and Herzegovina" },
  { city: "Pristina", name: "Pristina International", iata: "PRN", country: "Kosovo" },

  // --- Additional US Private Jet Airports ---
  { city: "Boca Raton", name: "Boca Raton Airport", iata: "BCT", country: "United States" },
  { city: "Santa Barbara", name: "Santa Barbara Airport", iata: "SBA", country: "United States" },
  { city: "Sun Valley", name: "Friedman Memorial Airport", iata: "SUN", country: "United States" },
  { city: "Vail", name: "Eagle County Regional", iata: "EGE", country: "United States" },
  { city: "Telluride", name: "Telluride Regional", iata: "TEX", country: "United States" },
  { city: "Cabo San Lucas", name: "Los Cabos International", iata: "SJD", country: "Mexico" },
  { city: "Savannah", name: "Savannah/Hilton Head International", iata: "SAV", country: "United States" },
  { city: "Charleston", name: "Charleston International", iata: "CHS", country: "United States" },
  { city: "Napa", name: "Napa County Airport", iata: "APC", country: "United States" },
  { city: "Monterey", name: "Monterey Regional", iata: "MRY", country: "United States" },
  { city: "Sarasota", name: "Sarasota-Bradenton International", iata: "SRQ", country: "United States" },
  { city: "Norfolk", name: "Norfolk International", iata: "ORF", country: "United States" },
  { city: "Tulsa", name: "Tulsa International", iata: "TUL", country: "United States" },
  { city: "Oklahoma City", name: "Will Rogers World", iata: "OKC", country: "United States" },
  { city: "Omaha", name: "Eppley Airfield", iata: "OMA", country: "United States" },
  { city: "El Paso", name: "El Paso International", iata: "ELP", country: "United States" },
  { city: "Albuquerque", name: "Albuquerque International Sunport", iata: "ABQ", country: "United States" },
  { city: "Louisville", name: "Louisville International", iata: "SDF", country: "United States" },
  { city: "Boise", name: "Boise Airport", iata: "BOI", country: "United States" },
  { city: "Tucson", name: "Tucson International", iata: "TUS", country: "United States" },
  { city: "Birmingham", name: "Birmingham-Shuttlesworth International", iata: "BHM", country: "United States" },
  { city: "Little Rock", name: "Clinton National", iata: "LIT", country: "United States" },
  { city: "Greenville", name: "Greenville-Spartanburg International", iata: "GSP", country: "United States" },
  { city: "Knoxville", name: "McGhee Tyson", iata: "TYS", country: "United States" },
  { city: "Spokane", name: "Spokane International", iata: "GEG", country: "United States" },
  { city: "Fresno", name: "Fresno Yosemite International", iata: "FAT", country: "United States" },

  // --- Additional Asia-Pacific ---
  { city: "Luang Prabang", name: "Luang Prabang International", iata: "LPQ", country: "Laos" },
  { city: "Langkawi", name: "Langkawi International", iata: "LGK", country: "Malaysia" },
  { city: "Lombok", name: "Lombok International", iata: "LOP", country: "Indonesia" },
  { city: "Yogyakarta", name: "Yogyakarta International", iata: "YIA", country: "Indonesia" },
  { city: "Bandung", name: "Husein Sastranegara", iata: "BDO", country: "Indonesia" },
  { city: "Nha Trang", name: "Cam Ranh International", iata: "CXR", country: "Vietnam" },
  { city: "Phu Quoc", name: "Phu Quoc International", iata: "PQC", country: "Vietnam" },
  { city: "Chiang Rai", name: "Mae Fah Luang", iata: "CEI", country: "Thailand" },
  { city: "Hat Yai", name: "Hat Yai International", iata: "HDY", country: "Thailand" },
  { city: "Clark", name: "Clark International", iata: "CRK", country: "Philippines" },
  { city: "Davao", name: "Francisco Bangoy International", iata: "DVO", country: "Philippines" },
  { city: "Boracay", name: "Godofredo P. Ramos Airport", iata: "MPH", country: "Philippines" },
  { city: "Okinawa", name: "Naha Airport", iata: "OKA", country: "Japan" },
  { city: "Hiroshima", name: "Hiroshima Airport", iata: "HIJ", country: "Japan" },
  { city: "Sendai", name: "Sendai Airport", iata: "SDJ", country: "Japan" },
  { city: "Kumamoto", name: "Aso Kumamoto Airport", iata: "KMJ", country: "Japan" },
  { city: "Xiamen", name: "Gaoqi International", iata: "XMN", country: "China" },
  { city: "Dalian", name: "Zhoushuizi International", iata: "DLC", country: "China" },
  { city: "Sanya", name: "Phoenix International", iata: "SYX", country: "China" },
  { city: "Guilin", name: "Liangjiang International", iata: "KWL", country: "China" },
  { city: "Zhengzhou", name: "Xinzheng International", iata: "CGO", country: "China" },
  { city: "Changsha", name: "Huanghua International", iata: "CSX", country: "China" },
  { city: "Qingdao", name: "Jiaodong International", iata: "TAO", country: "China" },
  { city: "Tianjin", name: "Binhai International", iata: "TSN", country: "China" },
  { city: "Harbin", name: "Taiping International", iata: "HRB", country: "China" },
  { city: "Lhasa", name: "Gonggar Airport", iata: "LXA", country: "China" },
  { city: "Ürümqi", name: "Diwopu International", iata: "URC", country: "China" },

  // --- Additional ---
  { city: "Luxor", name: "Luxor International", iata: "LXR", country: "Egypt" },
  { city: "Aswan", name: "Aswan International", iata: "ASW", country: "Egypt" },
  { city: "Alexandria", name: "Borg El Arab", iata: "HBE", country: "Egypt" },
  { city: "Djerba", name: "Djerba-Zarzis International", iata: "DJE", country: "Tunisia" },
  { city: "Agadir", name: "Al Massira Airport", iata: "AGA", country: "Morocco" },
  { city: "Fez", name: "Saïss Airport", iata: "FEZ", country: "Morocco" },
  { city: "Recife", name: "Guararapes International", iata: "REC", country: "Brazil" },
  { city: "Salvador", name: "Deputado Luís Eduardo Magalhães International", iata: "SSA", country: "Brazil" },
  { city: "Belo Horizonte", name: "Confins International", iata: "CNF", country: "Brazil" },
  { city: "Fortaleza", name: "Pinto Martins International", iata: "FOR", country: "Brazil" },
  { city: "Florianópolis", name: "Hercílio Luz International", iata: "FLN", country: "Brazil" },
  { city: "Porto Alegre", name: "Salgado Filho International", iata: "POA", country: "Brazil" },
  { city: "Curitiba", name: "Afonso Pena International", iata: "CWB", country: "Brazil" },
  { city: "Manaus", name: "Eduardo Gomes International", iata: "MAO", country: "Brazil" },
  { city: "Santa Cruz", name: "Viru Viru International", iata: "VVI", country: "Bolivia" },
  { city: "Córdoba", name: "Ingeniero Ambrosio Taravella", iata: "COR", country: "Argentina" },
  { city: "Mendoza", name: "Governor Francisco Gabrielli International", iata: "MDZ", country: "Argentina" },
  { city: "Bariloche", name: "San Carlos de Bariloche Airport", iata: "BRC", country: "Argentina" },

  // --- Remaining to reach 500+ ---
  { city: "Nice", name: "Nice Côte d'Azur (Private Terminal)", iata: "NCE", country: "France" },
  { city: "Olbia", name: "Costa Smeralda Airport", iata: "OLB", country: "Italy" },
  { city: "Mykonos", name: "Mykonos Island National", iata: "JMK", country: "Greece" },
  { city: "Zakynthos", name: "Dionysios Solomos", iata: "ZTH", country: "Greece" },
  { city: "Kalamata", name: "Captain Vassilis Constantakopoulos", iata: "KLX", country: "Greece" },
  { city: "Kos", name: "Kos Island International", iata: "KGS", country: "Greece" },
  { city: "Skiathos", name: "Alexandros Papadiamantis", iata: "JSI", country: "Greece" },
  { city: "Preveza", name: "Aktion Airport", iata: "PVK", country: "Greece" },
  { city: "Chania", name: "Ioannis Daskalogiannis", iata: "CHQ", country: "Greece" },
  { city: "Maastricht", name: "Maastricht Aachen Airport", iata: "MST", country: "Netherlands" },
  { city: "Groningen", name: "Groningen Airport Eelde", iata: "GRQ", country: "Netherlands" },
  { city: "Antwerp", name: "Antwerp International", iata: "ANR", country: "Belgium" },
  { city: "Liege", name: "Liège Airport", iata: "LGG", country: "Belgium" },
  { city: "Nürnberg", name: "Nürnberg Airport", iata: "NUE", country: "Germany" },
  { city: "Leipzig", name: "Leipzig/Halle Airport", iata: "LEJ", country: "Germany" },
  { city: "Dresden", name: "Dresden Airport", iata: "DRS", country: "Germany" },
  { city: "Bremen", name: "Bremen Airport", iata: "BRE", country: "Germany" },
  { city: "Dortmund", name: "Dortmund Airport", iata: "DTM", country: "Germany" },
  { city: "Karlsruhe", name: "Karlsruhe/Baden-Baden Airport", iata: "FKB", country: "Germany" },
  { city: "Friedrichshafen", name: "Friedrichshafen Airport", iata: "FDH", country: "Germany" },
  { city: "Linz", name: "Blue Danube Airport", iata: "LNZ", country: "Austria" },
  { city: "Graz", name: "Graz Airport", iata: "GRZ", country: "Austria" },
  { city: "Bern", name: "Bern Airport", iata: "BRN", country: "Switzerland" },
  { city: "Shannon", name: "Shannon Airport", iata: "SNN", country: "Ireland" },
  { city: "Cork", name: "Cork Airport", iata: "ORK", country: "Ireland" },
  { city: "Billund", name: "Billund Airport", iata: "BLL", country: "Denmark" },
  { city: "Aalborg", name: "Aalborg Airport", iata: "AAL", country: "Denmark" },
  { city: "Aarhus", name: "Aarhus Airport", iata: "AAR", country: "Denmark" },
  { city: "Visby", name: "Visby Airport", iata: "VBY", country: "Sweden" },
  { city: "Luleå", name: "Luleå Airport", iata: "LLA", country: "Sweden" },
  { city: "Oulu", name: "Oulu Airport", iata: "OUL", country: "Finland" },
  { city: "Rovaniemi", name: "Rovaniemi Airport", iata: "RVN", country: "Finland" },
  { city: "Gaziantep", name: "Oğuzeli Airport", iata: "GZT", country: "Turkey" },
  { city: "Trabzon", name: "Trabzon Airport", iata: "TZX", country: "Turkey" },
  { city: "Adana", name: "Şakirpaşa Airport", iata: "ADA", country: "Turkey" },
  { city: "Kayseri", name: "Erkilet International", iata: "ASR", country: "Turkey" },
  { city: "Tbilisi", name: "Shota Rustaveli", iata: "TBS", country: "Georgia" },
  { city: "Batumi", name: "Batumi International", iata: "BUS", country: "Georgia" },
  { city: "Kutaisi", name: "David the Builder Kutaisi International", iata: "KUT", country: "Georgia" },
  { city: "Bishkek", name: "Manas International", iata: "FRU", country: "Kyrgyzstan" },
  { city: "Dushanbe", name: "Dushanbe International", iata: "DYU", country: "Tajikistan" },
  { city: "Ashgabat", name: "Ashgabat International", iata: "ASB", country: "Turkmenistan" },
  { city: "Samarkand", name: "Samarkand International", iata: "SKD", country: "Uzbekistan" },
];

// Remove exact duplicates (same IATA) - keep first occurrence
const seen = new Set<string>();
const uniqueAirports: Airport[] = [];
for (const airport of airports) {
  const key = airport.iata;
  if (!seen.has(key)) {
    seen.add(key);
    uniqueAirports.push(airport);
  }
}

export default uniqueAirports;
