import { AircraftProvider, NormalizedAircraft } from './types';

const SEED_AIRCRAFT: NormalizedAircraft[] = [
  // Light Jets
  {
    sourceProvider: 'seed',
    sourceId: 'seed-citation-cj3',
    name: 'Cessna Citation CJ3+',
    slug: 'cessna-citation-cj3-plus',
    manufacturer: 'Cessna',
    typeName: 'Light Jet',
    yearMin: 2014,
    yearMax: 2024,
    maxPassengers: 7,
    maxRange: 2040,
    cruiseSpeed: 416,
    cabinHeight: 4.8,
    cabinWidth: 4.8,
    cabinLength: 15.7,
    baggageVolume: 64,
    basePricePerHour: 3200,
    heroImage: 'https://images.unsplash.com/photo-1540962351504-03099e0a754b?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1540962351504-03099e0a754b?w=800&q=80',
      'https://images.unsplash.com/photo-1436491865332-7a61a109db05?w=800&q=80',
    ],
    description: 'The Citation CJ3+ offers the perfect blend of performance and efficiency. Ideal for short to medium-range trips with a comfortable cabin and excellent runway performance.',
    amenities: ['Wi-Fi', 'Leather Seating', 'Power Outlets', 'Lavatory', 'Climate Control', 'USB Charging'],
    featured: true,
  },
  {
    sourceProvider: 'seed',
    sourceId: 'seed-phenom-300e',
    name: 'Embraer Phenom 300E',
    slug: 'embraer-phenom-300e',
    manufacturer: 'Embraer',
    typeName: 'Light Jet',
    yearMin: 2020,
    yearMax: 2024,
    maxPassengers: 8,
    maxRange: 2010,
    cruiseSpeed: 453,
    cabinHeight: 4.9,
    cabinWidth: 5.1,
    cabinLength: 17.2,
    baggageVolume: 84,
    basePricePerHour: 3600,
    heroImage: 'https://images.unsplash.com/photo-1474302770737-173ee21bab63?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1474302770737-173ee21bab63?w=800&q=80',
      'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?w=800&q=80',
    ],
    description: 'The best-selling light jet in the world. The Phenom 300E delivers exceptional speed, range, and cabin comfort with Embraer\'s renowned build quality.',
    amenities: ['Wi-Fi', 'Entertainment System', 'Leather Seating', 'Power Outlets', 'Lavatory', 'Climate Control', 'USB Charging', 'Folding Tables'],
    featured: false,
  },
  {
    sourceProvider: 'seed',
    sourceId: 'seed-hondajet-elite',
    name: 'HondaJet Elite S',
    slug: 'hondajet-elite-s',
    manufacturer: 'Honda Aircraft',
    typeName: 'Light Jet',
    yearMin: 2021,
    yearMax: 2024,
    maxPassengers: 6,
    maxRange: 1547,
    cruiseSpeed: 422,
    cabinHeight: 4.8,
    cabinWidth: 5.0,
    cabinLength: 12.1,
    baggageVolume: 57,
    basePricePerHour: 2800,
    heroImage: 'https://images.unsplash.com/photo-1583416750893-01aee0570a43?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1583416750893-01aee0570a43?w=800&q=80',
    ],
    description: 'Innovative over-the-wing engine mount design delivers a quieter, more efficient flight experience. Perfect for owner-operators and short business trips.',
    amenities: ['Wi-Fi', 'Leather Seating', 'Power Outlets', 'Lavatory', 'Climate Control'],
    featured: false,
  },
  // Midsize Jets
  {
    sourceProvider: 'seed',
    sourceId: 'seed-citation-latitude',
    name: 'Cessna Citation Latitude',
    slug: 'cessna-citation-latitude',
    manufacturer: 'Cessna',
    typeName: 'Midsize Jet',
    yearMin: 2015,
    yearMax: 2024,
    maxPassengers: 9,
    maxRange: 2700,
    cruiseSpeed: 446,
    cabinHeight: 6.0,
    cabinWidth: 6.4,
    cabinLength: 21.1,
    baggageVolume: 100,
    basePricePerHour: 4500,
    heroImage: 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800&q=80',
      'https://images.unsplash.com/photo-1464037866556-6812c9d1c72e?w=800&q=80',
    ],
    description: 'The Citation Latitude redefines the midsize category with its flat-floor cabin, stand-up headroom, and impressive coast-to-coast range.',
    amenities: ['Wi-Fi', 'Entertainment System', 'Full Galley', 'Leather Seating', 'Power Outlets', 'Lavatory', 'Climate Control', 'USB Charging', 'Folding Tables', 'Luggage Compartment'],
    featured: true,
  },
  {
    sourceProvider: 'seed',
    sourceId: 'seed-hawker-900xp',
    name: 'Hawker 900XP',
    slug: 'hawker-900xp',
    manufacturer: 'Hawker Beechcraft',
    typeName: 'Midsize Jet',
    yearMin: 2007,
    yearMax: 2013,
    maxPassengers: 8,
    maxRange: 2950,
    cruiseSpeed: 466,
    cabinHeight: 5.75,
    cabinWidth: 6.0,
    cabinLength: 21.3,
    baggageVolume: 49,
    basePricePerHour: 4100,
    heroImage: 'https://images.unsplash.com/photo-1556388158-158ea5ccacbd?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1556388158-158ea5ccacbd?w=800&q=80',
    ],
    description: 'A proven midsize workhorse with excellent range and a wide, comfortable cabin. The Hawker 900XP is a favorite for transcontinental business travel.',
    amenities: ['Wi-Fi', 'Full Galley', 'Leather Seating', 'Power Outlets', 'Lavatory', 'Climate Control', 'Folding Tables'],
    featured: false,
  },
  // Super Midsize Jets
  {
    sourceProvider: 'seed',
    sourceId: 'seed-citation-sovereign',
    name: 'Cessna Citation Sovereign+',
    slug: 'cessna-citation-sovereign-plus',
    manufacturer: 'Cessna',
    typeName: 'Super Midsize Jet',
    yearMin: 2013,
    yearMax: 2021,
    maxPassengers: 9,
    maxRange: 3200,
    cruiseSpeed: 458,
    cabinHeight: 5.7,
    cabinWidth: 5.5,
    cabinLength: 25.3,
    baggageVolume: 135,
    basePricePerHour: 5200,
    heroImage: 'https://images.unsplash.com/photo-1570710891163-6d3b5c47248b?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1570710891163-6d3b5c47248b?w=800&q=80',
    ],
    description: 'Bridging the gap between midsize and large cabin jets, the Sovereign+ offers transcontinental range with super-midsize efficiency.',
    amenities: ['Wi-Fi', 'Entertainment System', 'Full Galley', 'Leather Seating', 'Power Outlets', 'Lavatory', 'Climate Control', 'USB Charging', 'Folding Tables', 'Luggage Compartment'],
    featured: false,
  },
  {
    sourceProvider: 'seed',
    sourceId: 'seed-challenger-350',
    name: 'Bombardier Challenger 350',
    slug: 'bombardier-challenger-350',
    manufacturer: 'Bombardier',
    typeName: 'Super Midsize Jet',
    yearMin: 2014,
    yearMax: 2024,
    maxPassengers: 10,
    maxRange: 3200,
    cruiseSpeed: 470,
    cabinHeight: 6.08,
    cabinWidth: 7.17,
    cabinLength: 25.2,
    baggageVolume: 106,
    basePricePerHour: 5800,
    heroImage: 'https://images.unsplash.com/photo-1488085061387-422e29b40080?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1488085061387-422e29b40080?w=800&q=80',
      'https://images.unsplash.com/photo-1540979388789-6cee28a1cdc9?w=800&q=80',
    ],
    description: 'The Challenger 350 sets the standard in the super-midsize category with its widest-in-class cabin, exceptional performance, and smooth ride quality.',
    amenities: ['Wi-Fi', 'Entertainment System', 'Full Galley', 'Satellite Phone', 'Leather Seating', 'Power Outlets', 'Lavatory', 'Climate Control', 'USB Charging', 'Folding Tables', 'Luggage Compartment', 'Crew Service'],
    featured: true,
  },
  // Heavy Jets
  {
    sourceProvider: 'seed',
    sourceId: 'seed-gulfstream-g450',
    name: 'Gulfstream G450',
    slug: 'gulfstream-g450',
    manufacturer: 'Gulfstream',
    typeName: 'Heavy Jet',
    yearMin: 2004,
    yearMax: 2018,
    maxPassengers: 14,
    maxRange: 4350,
    cruiseSpeed: 528,
    cabinHeight: 6.17,
    cabinWidth: 7.33,
    cabinLength: 45.1,
    baggageVolume: 169,
    basePricePerHour: 7200,
    heroImage: 'https://images.unsplash.com/photo-1583592643761-c2d47ff251be?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1583592643761-c2d47ff251be?w=800&q=80',
      'https://images.unsplash.com/photo-1565623833408-d77e39b88af6?w=800&q=80',
    ],
    description: 'The Gulfstream G450 delivers wide-cabin luxury with intercontinental range. Three living areas provide ample space for work, dining, and rest.',
    amenities: ['Wi-Fi', 'Entertainment System', 'Full Galley', 'Satellite Phone', 'Leather Seating', 'Power Outlets', 'Lavatory', 'Climate Control', 'USB Charging', 'Folding Tables', 'Luggage Compartment', 'Crew Service', 'Sleeping Configuration', 'Conference Table'],
    featured: true,
  },
  {
    sourceProvider: 'seed',
    sourceId: 'seed-falcon-900lx',
    name: 'Dassault Falcon 900LX',
    slug: 'dassault-falcon-900lx',
    manufacturer: 'Dassault Aviation',
    typeName: 'Heavy Jet',
    yearMin: 2010,
    yearMax: 2023,
    maxPassengers: 12,
    maxRange: 4750,
    cruiseSpeed: 481,
    cabinHeight: 6.17,
    cabinWidth: 7.67,
    cabinLength: 33.2,
    baggageVolume: 127,
    basePricePerHour: 6800,
    heroImage: 'https://images.unsplash.com/photo-1529686342540-1b43aec0df75?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1529686342540-1b43aec0df75?w=800&q=80',
    ],
    description: 'The tri-engine Falcon 900LX offers unmatched safety, steep-approach capability, and exceptional range. French engineering at its finest.',
    amenities: ['Wi-Fi', 'Entertainment System', 'Full Galley', 'Satellite Phone', 'Leather Seating', 'Power Outlets', 'Lavatory', 'Climate Control', 'USB Charging', 'Folding Tables', 'Luggage Compartment', 'Crew Service', 'Sleeping Configuration'],
    featured: false,
  },
  // Ultra Long Range
  {
    sourceProvider: 'seed',
    sourceId: 'seed-gulfstream-g650er',
    name: 'Gulfstream G650ER',
    slug: 'gulfstream-g650er',
    manufacturer: 'Gulfstream',
    typeName: 'Ultra Long Range',
    yearMin: 2014,
    yearMax: 2024,
    maxPassengers: 16,
    maxRange: 7500,
    cruiseSpeed: 561,
    cabinHeight: 6.42,
    cabinWidth: 8.5,
    cabinLength: 46.8,
    baggageVolume: 195,
    basePricePerHour: 11500,
    heroImage: 'https://images.unsplash.com/photo-1567581406955-18e42d3bc371?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1567581406955-18e42d3bc371?w=800&q=80',
      'https://images.unsplash.com/photo-1544016768-982d1554f0b9?w=800&q=80',
    ],
    description: 'The flagship of the Gulfstream fleet. The G650ER connects any two cities on Earth with uncompromising luxury, speed, and range.',
    amenities: ['Wi-Fi', 'Entertainment System', 'Full Galley', 'Satellite Phone', 'Leather Seating', 'Power Outlets', 'Lavatory', 'Climate Control', 'USB Charging', 'Folding Tables', 'Luggage Compartment', 'Crew Service', 'Sleeping Configuration', 'Shower', 'Conference Table'],
    featured: true,
  },
  {
    sourceProvider: 'seed',
    sourceId: 'seed-global-7500',
    name: 'Bombardier Global 7500',
    slug: 'bombardier-global-7500',
    manufacturer: 'Bombardier',
    typeName: 'Ultra Long Range',
    yearMin: 2018,
    yearMax: 2024,
    maxPassengers: 17,
    maxRange: 7700,
    cruiseSpeed: 516,
    cabinHeight: 6.17,
    cabinWidth: 8.0,
    cabinLength: 54.4,
    baggageVolume: 195,
    basePricePerHour: 12500,
    heroImage: 'https://images.unsplash.com/photo-1525624286412-4099c83c1bc8?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1525624286412-4099c83c1bc8?w=800&q=80',
    ],
    description: 'The world\'s largest and longest-range purpose-built business jet. Four true living spaces, a full kitchen, and a dedicated crew suite.',
    amenities: ['Wi-Fi', 'Entertainment System', 'Full Galley', 'Satellite Phone', 'Leather Seating', 'Power Outlets', 'Lavatory', 'Climate Control', 'USB Charging', 'Folding Tables', 'Luggage Compartment', 'Crew Service', 'Sleeping Configuration', 'Shower', 'Conference Table'],
    featured: false,
  },
  {
    sourceProvider: 'seed',
    sourceId: 'seed-citation-xls',
    name: 'Cessna Citation XLS+',
    slug: 'cessna-citation-xls-plus',
    manufacturer: 'Cessna',
    typeName: 'Midsize Jet',
    yearMin: 2008,
    yearMax: 2024,
    maxPassengers: 8,
    maxRange: 2100,
    cruiseSpeed: 441,
    cabinHeight: 5.7,
    cabinWidth: 5.5,
    cabinLength: 18.5,
    baggageVolume: 80,
    basePricePerHour: 3900,
    heroImage: 'https://images.unsplash.com/photo-1606768666853-403c90a981ad?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1606768666853-403c90a981ad?w=800&q=80',
    ],
    description: 'One of the most popular midsize jets ever built. The Citation XLS+ combines reliability, comfort, and operating efficiency.',
    amenities: ['Wi-Fi', 'Leather Seating', 'Power Outlets', 'Lavatory', 'Climate Control', 'USB Charging', 'Folding Tables'],
    featured: false,
  },
];

export class SeedProvider implements AircraftProvider {
  name = 'seed';
  enabled = true;

  async fetchAll(): Promise<NormalizedAircraft[]> {
    return SEED_AIRCRAFT;
  }

  async fetchById(sourceId: string): Promise<NormalizedAircraft | null> {
    return SEED_AIRCRAFT.find(a => a.sourceId === sourceId) || null;
  }

  async healthCheck(): Promise<boolean> {
    return true;
  }
}
